from define import Tag




TAG_ITEM = Tag("item")



TAG_WEARABLE = Tag("wearable", TAG_ITEM)
TAG_USABLE = Tag("usable", TAG_ITEM)



TAG_ARMOR = Tag("armor", TAG_WEARABLE)
TAG_CLOTHES = Tag("cloths", TAG_WEARABLE)
TAG_TRINKETS = Tag("trinkets", TAG_WEARABLE)


TAG_WEAPON = Tag("weapon", TAG_USABLE)
TAG_TOOL = Tag("tool", TAG_USABLE)



TAG_ARMOR_HEAD = Tag("head", TAG_ARMOR)
TAG_ARMOR_BODY = Tag("body", TAG_ARMOR)
TAG_ARMOR_HANDS = Tag("hands", TAG_ARMOR)
TAG_ARMOR_LEGS = Tag("legs", TAG_ARMOR)
TAG_ARMOR_FEET = Tag("feet", TAG_ARMOR)

TAG_CLOTHES_HEAD = Tag("head", TAG_CLOTHES)
TAG_CLOTHES_UPPPER_UNDIES = Tag("upperundies", TAG_CLOTHES)
TAG_CLOTHES_BODY = Tag("body", TAG_CLOTHES)
TAG_CLOTHES_HANDS = Tag("hands", TAG_CLOTHES)
TAG_CLOTHES_UNDERWEAR = Tag("lowerundies", TAG_CLOTHES)
TAG_CLOTHES_LEGS = Tag("legs", TAG_CLOTHES)
TAG_CLOTHES_SOCKS = Tag("feetundies", TAG_CLOTHES)
TAG_CLOTHES_FEET = Tag("feet", TAG_CLOTHES)

TAG_TRINKETS_FACE = Tag("face", TAG_TRINKETS)
TAG_TRINKETS_EAR = Tag("ear", TAG_TRINKETS)
TAG_TRINKETS_NECK = Tag("neck", TAG_TRINKETS)
TAG_TRINKETS_CAPE = Tag("cape", TAG_TRINKETS)
TAG_TRINKETS_WRIST = Tag("wrist", TAG_TRINKETS)
TAG_TRINKETS_HAND = Tag("hand", TAG_TRINKETS)
TAG_TRINKETS_FINGER = Tag("finger", TAG_TRINKETS)
TAG_TRINKETS_BELT = Tag("belt", TAG_TRINKETS)
TAG_TRINKETS_ANKLE = Tag("ankle", TAG_TRINKETS)


TAG_MASSIVE = Tag("massive", TAG_WEAPON)
TAG_HEAVY = Tag("heavy", TAG_WEAPON)
TAG_MEDIUM = Tag("medium", TAG_WEAPON)
TAG_LIGHT = Tag("light", TAG_WEAPON)
TAG_BOW = Tag("bow", TAG_WEAPON)